fix(Escape Labels/Annotations that contain special characters)
ExpediaGroup/kubernetes-sidecar-injector pull request #51
Opened 2022-08-09 22:55 UTC by mwm5945

### :pencil: Description
- Many labels/annotations use `/` and `~` (though far more the former). However that is also a special character in json patching. These characters simply need to be escaped before the patch is created. 

### :pencil: Customer Notes
- _Provide relevant details for customers - what changed from a configuration perspective and/or what changes do they
need to incorporate in order to upgrade to this version?_
n/a

### :heavy_check_mark: Checklist
- [x] [Semantic Versioning](https://semver.org/) present in commit message.

### [Semantic Versioning](https://semver.org/)
1. fix(pencil): patches a bug ([PATCH](http://semver.org/#summary)); e.g., fix(pencil): fixed a bug
2. feat(pencil): new feature ([MINOR](http://semver.org/#summary)); e.g., feat(pencil): added a feature
3. BREAKING CHANGE/perf(pencil): footer BREAKING CHANGE:, breaking change ([MAJOR](http://semver.org/#summary)); e.g., perf(pencil): api change

2022-08-09 22:56 UTC, mwm5945 commented
@mvaalexp FYI :)

2022-08-10 19:12 UTC, mvaalexp submitted a review, later dismissed
Thanks!

2022-08-10 19:16 UTC, mvaalexp requested changes
would you mind adding a test for `~` (to `~0`) as well please?
otherwise looks good

2022-08-10 19:38 UTC, mwm5945 commented
@mvaalexp done!

2022-08-10 19:40 UTC, mvaalexp approved these changes

2022-08-10 19:41 UTC, merged